# Base configs
baseurl: "https://churchillcat.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-TWPZKR2RBH"

# UI configs
title: "In memory of our beloved Churchill"
subtitle: "Churchill in the Heaven"
author: "Churchill's parents"
header:
 title: "Churchill"
 subtitle: "in the wonderland"
footer:
 name: "Hey there, this is Churchill! Greetings from the above."
 bio: "I am an exotic shorthair kitty born in July the 4th, 2020. Yes! I am patriotic! I wish you happy and please don't shed tears for me anymore."
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
# web_design: "Winston Li"
# social_urls:
#   facebook: "https://www.facebook.com/ramswaroop"
#   twitter: "https://www.twitter.com/ram__patra"
#   instagram: "https://www.instagram.com/ram_patra"
#   dribbble: "https://dribbble.com/rampatra"
#   linkedin: "https://in.linkedin.com/in/ram-patra"
#   github: "https://www.github.com/rampatra"
